name: Terraform and TFLint

on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.0.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Terraform and TFLint
        run: |
          cd /usr/bin
          curl -s -qL -o terraform.zip "https://releases.hashicorp.com/terraform/${{ env.TF_VERSION }}/terraform_${{ env.TF_VERSION }}_linux_amd64.zip"
          unzip -o terraform.zip
          curl --location "https://github.com/terraform-linters/tflint/releases/download/v0.33.0/tflint_linux_amd64.zip" --output tflint_linux_amd64.zip
          unzip -o tflint_linux_amd64.zip

      - name: Initialize Terraform
        run: cd ${{ github.workspace }} && terraform init

      - name: Validate Terraform
        run: cd ${{ github.workspace }} && terraform validate

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint

      - name: Post Build Steps
        run: |
          echo "terraform validate completed on $(date)"
          echo "tflint completed on $(date)"
