name: Terraform and TFLint

on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.0.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: TFLint
        run: |
          sudo cd /usr/bin
          curl --location "https://github.com/terraform-linters/tflint/releases/download/v0.33.0/tflint_linux_amd64.zip" --output tflint_linux_amd64.zip
          unzip -o tflint_linux_amd64.zip

      - name: Initialize Terraform
        run: cd ${{ github.workspace }} && terraform init

      - name: Validate Terraform
        run: cd ${{ github.workspace }} && terraform validate

      - name: Initialize TFLint
        run: tflint --init

      - name: Run TFLint
        run: tflint

      - name: Post Build Steps
        run: |
          echo "terraform validate completed on $(date)"
          echo "tflint completed on $(date)"
