name: Terraform and TFLint

on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.0.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Install TFLint
        run:
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          
      - name: Create ssh key pair
        run: ssh-keygen -f ~/.ssh/Oregon2key <<<y >/dev/null 2>&1

      - name: Run checks
        run: |
          cd ${{ github.workspace }}
          terraform init
          terraform validate
          tflint --init
          tflint

      - name: Post Build Steps
        run: |
          echo "terraform validate completed on $(date)"
          echo "tflint completed on $(date)"
