name: Terraform Validate and TFLint

on:
  push:
    branches:
      - main

env:
  TF_VERSION: "1.4.6"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2

      - name: Install TFLint
        run:
          curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
          
      - name: Create ssh key pair
        run: ssh-keygen -f ~/.ssh/Oregon2key <<<y >/dev/null 2>&1

      - name: Validate terraform
        run: |
          cd ${{ github.workspace }}
          echo "- Running terraform init -"
          terraform init
          echo "- Running terraform validate -"
          terraform validate

      - name: Run tflint
        run: |
          echo "- Running tflint --init -"
          tflint --init
          echo "- Running tflint validate -"
          tflint

      - name: Post Build Steps
        run: |
          echo "terraform validate completed on $(date)"
          echo "tflint completed on $(date)"
